development: &default
  adapter: postgresql
  host: localhost
  database: tour_conf_development
  username: root
  password:
  min_messages: WARNING
  template: template0

test: &test
  <<: *default
  database: tour_conf_test<%= ENV['TEST_ENV_NUMBER'] %>

